### ISSUE TITLE
Solution notebook

### ISSUE THREAD

**Issue by cpsanchez** [ScienceBetter/notebooks-stsci#8]
Reminder to decide how to proceed with the solution notebook, whether to upload two (one only with the exercises and one with the exercises + solutions), directly upload the one with the exercises + solutions, or else.

**Comment by kelle** [comment]
I vote that we upload a 2nd dedicated notebook with the exercise solutions. It doesn't need to have the entire tutorial duplicated, it can just be the exercises worked out.

**Comment by ttdutkiewicz** [comment]
I second the vote for a 2nd dedicated notebook. Better for users and consistent with the style guide.

**Comment by cpsanchez** [comment]
I agree! I uploaded the first version of the solutions notebook for the UV_extinction_curves tutorials with only the solutions of the exercises as well as the actual tutorial that includes the exercises for the users to try.
